--- #YAML:1.0
name:                Image-PBMlib
version:             2.00
abstract:            Helper functions for PBM/PGM/PPM image file formats
license:             ~
author:              
    - Benjamin Elijah Griffin / Eli the Bearded <elijah@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
